name: Repository Activity

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Git config
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
      - name: Create new branch
        run: |
          current_date=$(date +%Y%m%d_%H%M%S)
          branch_name="auto-update-${current_date}"
          git checkout -b $branch_name
          
      - name: Update activity file
        run: |
          mkdir -p .github/activity
          echo "Last updated: $(date)" > .github/activity/latest-update.txt
          git add .github/activity/latest-update.txt
          
      - name: Commit changes
        run: |
          git commit -m "Auto update repository activity [skip ci]"
          
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD
          gh pr create \
            --title "Auto Repository Update $(date +%Y-%m-%d)" \
            --body "This is an automated pull request to keep the repository active.\n\nChanges made:\n- Updated activity timestamp" \
            --label "automated" \
            --base main
