name: NodeJS with Gulp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        npm install -g gulp-cli

    - name: Cache Gulp tasks
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
          ~/.npm
        key: ${{ runner.os }}-gulp-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-gulp-

    - name: Build
      run: gulp build

    - name: Test
      run: gulp test

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: gulp-build
        path: dist/
